version: '3'
services:
  redis:
    image: redis
    command: [ "redis-server", "--appendonly", "yes" ]
    hostname: redis
    ports:
      - 6379:6379
    networks:
      - redis-net
    volumes:
      - redis-data:/data

  mysql-block:
    restart: always
    container_name: mysql-block
    image: mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: Ktjyfhlj2002
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - redis-net

    ports:
      - "6033:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=Ktjyfhlj2002--execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10

  article-block:
    restart: on-failure
    build: ./
    links:
      - redis
    expose:
      - "8089"
    ports:
      - 8089:8089
    environment:
      WAIT_HOSTS: mysql:3306
    depends_on:
      - mysql-block
      - redis
    networks:
      - redis-net

networks:
  redis-net:

volumes:
  redis-data: